name: AZ-400 Capstone Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Project Files
        run: |
          echo "Repository Contents:"
          ls -R

      - name: Validate HTML Exists
        run: |
          if [ ! -f app/index.html ]; then
            echo "index.html not found!"
            exit 1
          fi

      - name: Upload Website Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: app/

  security_scan:
    name: Gitleaks Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-staging:
    name: Deploy to Azure Staging
    runs-on: ubuntu-latest
    needs: security_scan

    environment:
      name: Staging

    steps:
      - name: Download Website Artifact
        uses: actions/download-artifact@v4
        with:
          name: website

      - name: Deploy to Azure Staging Slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: az400-capstone-yash
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_STAGING_PUBLISH_PROFILE }}
          package: .

  deploy-production:
    name: Deploy to Azure Production
    runs-on: ubuntu-latest
    needs: deploy-staging

    environment:
      name: production

    steps:
      - name: Download Website Artifact
        uses: actions/download-artifact@v4
        with:
          name: website

      - name: Deploy to Azure Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: az400-capstone-yash
          publish-profile: ${{ secrets.AZURE_PROD_PUBLISH_PROFILE }}
          package: .